version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: books-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    image: oarw/books-server:latest # 🟢 Pull from Docker Hub
    container_name: books-server
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/bookStore
      - PORT=5001
      - JWT_SECRET=your-secret-key

  client:
    image: oarw/books-client:latest # 🟢 Pull from Docker Hub
    container_name: books-client
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - server

volumes:
  mongo_data:
