services:
  mongo:
    image: mongo:latest
    container_name: books-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: books-server
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/bookStore
      - PORT=5001
      - JWT_SECRET=your-secret-key
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: books-client
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongo_data:
